### ISSUE TITLE
Hi, is it possible to train at a higher sample rate?

### ISSUE THREAD

**Issue by fan455** [lrenault/ddsp-piano#1]

**Comment by lrenault** [comment]
Hello,

Absolutely, you can change the `sample_rate` argument when:
- building the model (with `get_model()` and `build_model()` from `default_model.py`).
- loading the audio data (with `data_pipeline.get_training_dataset`).

You may also need to increase the dimensions of the `magnitudes` and `harmonic_distribution` outputs of the monophonic sub-module to keep the same frequency resolution of the noise synthesizer, among others.

Beware that increasing all those parameters would probably lead to memory complications on the GPU, as the default configuration at 16kHz was optimized to barely fit on a single GPU of ours...

Please note that, as of writing, the code is still being re-factorized and the code structure can still change, but specifying the sample rate is definitely a feature that will be kept.

Best,
