### ISSUE TITLE
ModuleNotFoundError: No module named 'priv_ddfx'

### ISSUE THREAD

**Issue by chunping-xt** [lrenault/ddsp-piano#6]
Thank you for your research and sharing. I tried with the main repo and there was no problem, but when I tried with the dev repo I got the error: ModuleNotFoundError: No module named 'priv_ddfx'
I think your repo is missing module priv_ddfx.py?

**Comment by lrenault** [comment]
Hello,
Currently, `prix_ddfx` is an internal private repository that our team has developed and provide new layers that updated versions of `ddsp-piano` can rely on.
It is still being discussed whether `priv-ddfx` will be released publicly or if we will solely import the relevant code in the `ddsp-piano` repo.

As a rule of thumb, all branches, except main, are used for internal development and are not fully tested.
When the code will be stable and ready for external usage, it will be merged into the main branch.

Best regards

**Comment by chunping-xt** [comment]
Great! Looking forward to it.
Best regards

**Comment by lrenault** [comment]
Update : the operations from `priv_ddfx` have been integrated in the main codebase, and released in the recent v2.0 update !
